### ISSUE TITLE
The integration stops working after mos.ru API update

### ISSUE THREAD

**Issue by Spirituss** [alryaz/hass-moscow-pgu#23]
Home assistant log:

```
ERROR (MainThread) [homeassistant.components.sensor] moscow_pgu: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_device_update
    await self.async_update()
  File "/config/custom_components/moscow_pgu/sensor.py", line 495, in async_update
    await super().async_update()
  File "/config/custom_components/moscow_pgu/sensor.py", line 323, in async_update
    offenses = await self.async_retrieve_offenses()
  File "/config/custom_components/moscow_pgu/sensor.py", line 487, in async_retrieve_offenses
    return await self.source.get_offenses()
  File "/config/custom_components/moscow_pgu/api.py", line 1989, in get_offenses
    return await self.api.get_vehicle_offenses(self.certificate_series)
  File "/config/custom_components/moscow_pgu/api.py", line 543, in get_vehicle_offenses
    result = await self.request(
  File "/config/custom_components/moscow_pgu/api.py", line 297, in request
    raise cache_future.exception()
  File "/config/custom_components/moscow_pgu/api.py", line 293, in request
    result = await self.uncached_request(sub_url, json=json)
  File "/config/custom_components/moscow_pgu/api.py", line 248, in uncached_request
    raise ResponseError(error_code, response.get("errorMessage", "no message"))
custom_components.moscow_pgu.api.ResponseError: Response error [10404]: Данный метод более не поддерживается. За подробностями обращайтесь в СТП ГИС ЕМП.
```

**Comment by maxdobmax** [comment]
Все закончилась интеграция так и не начавшись?

**Comment by Spirituss** [comment]
Интеграцию мало сделать, ее надо еще и поддерживать ...

**Comment by maxdobmax** [comment]
![image](https://github.com/alryaz/hass-moscow-pgu/assets/79459078/e34bd886-f112-4537-ac24-41a6f9cceeec)
Давайте задонатим автору как следует, чтобы его замотивировать?

**Comment by iereus** [comment]
Жаль, а я только обрадовался, что смогу мониторить выход из школы ребенка
