### ISSUE TITLE
Self Signed Certificate Error

### ISSUE THREAD

**Issue by shammysha** [alryaz/hass-moscow-pgu#5]
Не смог активировать интеграцию, пока не установил в api.py (строка 226) 

**ssl=False**

```   
async def uncached_request(self, sub_url: str, json: Optional[Mapping[str, Any]] = None) -> Any:
      ........
         async with self.client_session.post(full_url, ssl=False, params=params, json=json_data) as request:
      ........
```

В противном случае выдавалась ошибка

**[SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain** 
```
Traceback (most recent call last):
  File "/var/www/homeassistant/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/homeassistant/lib/python3.8/site-packages/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/var/lib/asterisk/.homeassistant/custom_components/moscow_pgu/__init__.py", line 324, in async_setup_entry
    await async_authenticate_api_object(hass, api_object)
  File "/var/lib/asterisk/.homeassistant/custom_components/moscow_pgu/util.py", line 84, in async_authenticate_api_object
    return await api.get_profile()
  File "/var/lib/asterisk/.homeassistant/custom_components/moscow_pgu/api.py", line 441, in get_profile
    result = await self.request("v1.0/profile/get")
  File "/var/lib/asterisk/.homeassistant/custom_components/moscow_pgu/api.py", line 281, in request
    result = await self.uncached_request(sub_url, json=json)
  File "/var/lib/asterisk/.homeassistant/custom_components/moscow_pgu/api.py", line 226, in uncached_request
    async with self.client_session.post(full_url, params=params, json=json_data) as request:
  File "/var/www/homeassistant/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/var/www/homeassistant/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/var/www/homeassistant/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/var/www/homeassistant/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/var/www/homeassistant/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/var/www/homeassistant/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/var/www/homeassistant/lib/python3.8/site-packages/aiohttp/connector.py", line 971, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host emp.mos.ru:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)')]
```

**Comment by alryaz** [comment]
Пожалуйста, убедитесь, что проблема не в Вашей сети (и в перехвате трафика SSL)

Я могу добавить флаг, чтобы игнорировать SSL, однако это может символизировать совсем другое.

**Comment by shammysha** [comment]
Может вынести в настройки на страх и риск пользователя?

**Comment by alryaz** [comment]
С одной стороны, соглашусь, что на страх и риск пользователя можно было бы вынести такую настройку, **если и только если** пользователь понимает, почему происходит такая ошибка.

Примерный случай случайного включения опции с теоретическими плачевными последствиями: если неуспешная авторизация, которая была отклонена сервером из-за, например, вспышки на солнце (или иного события, косвенно влияющего на стандартный алгоритм авторизации), и затем была произведена повторно с отключением верификации SSL, но уже успешно, то это лишь приведёт к тому, что конфигурация будет постоянно работать без верификации.

**Comment by alryaz** [comment]
Сейчас на main висит коммит, который добавляет такую возможность. @shammysha, Вы можете попробовать установить данную версию, однако это лишь решит вопрос того, чтобы ошибка не вылезала. Если у Вас самоподписанный сертификат, то добавьте его CA в список одобренных (пример: https://stackoverflow.com/a/52961564).
