### ISSUE TITLE
After last (today) update

### ISSUE THREAD

**Issue by frfstu** [alryaz/hass-moscow-pgu#9]
After last update

Эта ошибка возникла в кастомной интеграции.

Logger: homeassistant.config_entries
Source: custom_components/moscow_pgu/__init__.py:116
Integration: Госуслуги Москвы (documentation, issues)
First occurred: 20:42:34 (1 occurrences)
Last logged: 20:42:34

Error setting up entry  for moscow_pgu
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/moscow_pgu/__init__.py", line 116, in async_setup_entry
    final_config = CONFIG_ENTRY_SCHEMA({**config_entry.data, **config_entry.options})
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['app_version']

**Comment by frfstu** [comment]
Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.moscow_pgu.sensor
Source: custom_components/moscow_pgu/sensor.py:960
Integration: Госуслуги Москвы (documentation, issues)
First occurred: 14 октября 2021 г., 22:18:08 (1 occurrences)
Last logged: 14 октября 2021 г., 22:18:08

Error on indications status update: Response error [8000]: Неверный тип переданных данных

**Comment by alryaz** [comment]
@DieMetRik , @frfstu пожалуйста, проверьте версию v0.2.5
